
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: twapp_development

test:
  <<: *default
  database: twapp_test

production:
  <<: *default
  database: twapp_production
  username: twapp
  password: <%= ENV['TWAPP_DATABASE_PASSWORD'] %>
